<a href="<?php echo $this->app->urlFor('TodoLists:index'); ?>">Back to all lists</a>
<h1><?php echo $list->name; ?></h1>
<div id="todo-list-items">
  <?php foreach($list->items as $item): ?>
    <div class="todo-list-item <?php echo $item->done ? 'checked': 'not-checked'; ?>">
      <div class="name">
        <?php echo $item->name; ?>
      </div>
      <div class="action">
        <form action="<?php echo $this->app->urlFor('TodoList\\TodoItems:edit', array('listId' => $list->id, 'id' => $item->id)); ?>" method="post">
          <input type="hidden" value="<?php echo $item->done ? 'uncheck' : 'check'; ?>" name="action">
          <button type="submit">
            <?php echo $item->done ? 'Uncheck' : 'Check'; ?>
          </button>
        </form>
      </div>
    </div>
  <?php endforeach; ?>
</div>
