<!DOCTYPE html>
<html>
  <head>
    <title><?php echo $title ? $title . ' | ': ''; ?>Todo Slimcontroller App</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/reset.css">
    <link rel="stylesheet" href="/css/style.css">
  </head>
  <body>
    <div class="container">
      <?php echo $yield; ?>
    </div>
    <script src="/js/script.js"></script>
  </body>
</html>
